services:
  webtop:
    image: cs233illinois/webtop-spimbot
    container_name: webtop-spimbot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - .:/config/Desktop/shared
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
